name: Security

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          check-latest: true
          # Default command: govulncheck ./...

  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true
      - uses: securego/gosec@master
        with:
          args: ./...

